//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfileMgmtDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int uID { get; set; }
        public int pID { get; set; }
        public System.DateTime createdOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Profile profile { get; set; }
        public virtual User user { get; set; }
    }
}
